language: node_js
node_js:
  - "5"

cache:
  directories:
  - node_modules

addons:
  firefox: "45"

before_script:
  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "echo $TRAVIS_NODE_VERSION"
  - "echo $(nvm which $TRAVIS_NODE_VERSION)"
  - "echo $TRAVIS_FIREFOX_VERSION"
  - "echo $(which $TRAVIS_FIREFOX_VERSION)"
  - "export NODE_EXEC=$(nvm which $TRAVIS_NODE_VERSION)"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 5 # give xvfb some time to start

script: npm test