language: node_js
sudo: required
dist: trusty
node_js:
  - "5"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable
      - google-chrome-beta

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # fire up xvfb on port :99.0
  # setup app
  - "npm install"
  - "export NODE_EXEC=$(nvm which $TRAVIS_NODE_VERSION)"
  - "npm test &"
  # give App some time to start
  - "sleep 10"
  - chmod +x ./run_tests
  - chmod +x ./nightwatch

script: ./run_tests
