language: node_js

node_js:
  - "5"

git:
  depth: 3

cache:
  directories:
  - node_modules

#before_install:
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  # fire up xvfb on port :99
  # - "sh -e /etc/init.d/xvfb start"
  - "sudo aptitude -y -q install unzip chromium-browser"
  # set the xvfb screen size to 1280x1024x16
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start
  - "export NODE_EXEC=$(nvm which $TRAVIS_NODE_VERSION)"
  #- "Xvfb :10 -screen 0 1366x768x24 -ac"
  #- "export DISPLAY:10"
  #- "google-chrome --remote-debugging-port=9222 --sandbox"
  #- "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  #- "export DISPLAY=:99"
  #- sleep 3 # give xvfb some time to start

script: npm test
