language: node_js
sudo: required
node_js:
  - "5"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  # fire up xvfb on port :99.0
  - chmod +x ./setup-selenium-chrome.sh
  - ./setup-selenium-chrome.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # setup Meteor app
  - "npm install"
  - "export NODE_EXEC=$(nvm which $TRAVIS_NODE_VERSION)"
  - "export GOOGLE_EXEC=$(which google-chrome)"
  - "npm test &"
  # give Meteor some time to start
  - "sleep 10"

install:
  # Add Google Chrome's repo to sources.list
  #- echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list

  # Install Google's public key used for signing packages (e.g. Chrome)
  # (Source: http://www.google.com/linuxrepositories/)
  #- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

  # Update apt sources:
  #- apt-get update
  #- npm install protractor -g
  #- webdriver-manager update
  #- ln /usr/lib/node_modules/protractor/selenium/chromedriver /usr/bin/chromedriver
  #- "apt-get -y install default-jre"  # if not installed yet
  
  #- "apt-get -y install libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4"
  #- "apt-get -y install google-chrome-stable"
  # Dependencies to make "headless" chrome/selenium work:
  #- "apt-get -y install xvfb gtk2-engines-pixbuf"
  #- "apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable"

  # Optional but nifty: For capturing screenshots of Xvfb display:
  #- "apt-get -y install imagemagick x11-apps"

before_script:
  - chmod +x ./run_tests
  - chmod +x ./nightwatch

script: ./run_tests
